import React,{useMemo,useState}from'react'
import ogor from'./generated/ogor.json'
import{buildAssistant,usageKeyFor}from'./core/rulesEngine'
import{createGameState,markAbilityUsed,nextStep}from'./core/gameState'
import{loadState,saveState}from'./core/persistence'

const PHASE_LABELS={startOfTurn:'Inicio del turno',heroPhase:'Fase de héroe',movementPhase:'Movimiento',shootingPhase:'Disparo',chargePhase:'Carga',combatPhase:'Combate',endOfTurn:'Final del turno'}
const emptyModel=()=>({armies:[],editingArmyId:null,activeGame:null})
const makeId=()=>crypto.randomUUID()
const armyPoints=army=>army.units.reduce((total,unit)=>{const warscroll=ogor.warscrolls.find(item=>item.id===unit.warscrollId);return total+Number(warscroll?.points||0)*Number(unit.copies||1)},0)
const ActionCard=({row,onUse})=><article className="action-card"><div className="action-head"><div><span className="unit-kicker">{row.warscroll.name}</span><h3>{row.ability.name}</h3></div>{row.ability.cpCost?<span className="pill">{row.ability.cpCost} PC</span>:null}</div><p className="timing">{row.ability.phaseDetails||PHASE_LABELS[row.ability.phase]||'Timing sin normalizar'}</p>{row.ability.declare?<p><strong>Declarar:</strong> {row.ability.declare}</p>:null}{row.ability.effect?<p><strong>Efecto:</strong> {row.ability.effect}</p>:null}<p className="source-note">Texto original del dataset upstream · evaluación conservadora del timing.</p>{onUse?<button onClick={()=>onUse(row)}>✓ Marcar como utilizada</button>:null}</article>

function App(){
 const persisted=loadState()
 const[model,setModel]=useState(persisted||emptyModel())
 const[newName,setNewName]=useState('Mis Ogors')
 const[newLimit,setNewLimit]=useState(2000)
 const[selectedWarscrollId,setSelectedWarscrollId]=useState(ogor.warscrolls[0]?.id||'')
 const commit=next=>{setModel(next);saveState(next)}
 const createArmy=event=>{event.preventDefault();const army={id:makeId(),name:newName.trim()||'Mis Ogors',faction:ogor.faction.name,pointsLimit:Number(newLimit)||2000,units:[]};commit({...model,armies:[...model.armies,army],editingArmyId:army.id})}
 const editingArmy=model.armies.find(item=>item.id===model.editingArmyId)
 const activeArmy=model.armies.find(item=>item.id===model.activeGame?.armyId)
 const updateArmy=army=>commit({...model,armies:model.armies.map(item=>item.id===army.id?army:item)})
 const addUnit=()=>{if(!editingArmy||!selectedWarscrollId)return;updateArmy({...editingArmy,units:[...editingArmy.units,{instanceId:makeId(),warscrollId:selectedWarscrollId,copies:1,isGeneral:false}]})}
 const catalogById=useMemo(()=>new Map(ogor.warscrolls.map(item=>[item.id,item])),[])
 if(model.activeGame&&activeArmy){
  const assistant=buildAssistant(activeArmy,ogor.warscrolls,model.activeGame)
  const useAbility=row=>{const usageKey=usageKeyFor(row.ability,model.activeGame);if(!usageKey)return;commit({...model,activeGame:markAbilityUsed(model.activeGame,row.actionKey,usageKey)})}
  return <main className="app-shell"><header className="hero compact"><span className="eyebrow">BATTLE COMPANION · AOS</span><h1>{activeArmy.name}</h1><p>{activeArmy.faction} · {armyPoints(activeArmy)} / {activeArmy.pointsLimit} pts</p></header><section className="game-status"><div><span>Ronda</span><strong>{model.activeGame.round}</strong></div><div><span>Turno</span><strong>{model.activeGame.activePlayer==='you'?'Mi turno':'Turno rival'}</strong></div><div><span>Momento</span><strong>{PHASE_LABELS[model.activeGame.phase]}</strong></div></section><section className="section-block"><div className="section-title"><span className="status-dot green"/><h2>Ahora</h2><b>{assistant.available.length}</b></div>{assistant.available.length?assistant.available.map(row=><ActionCard key={row.actionKey} row={row} onUse={useAbility}/>):<p className="empty">No hay acciones normalizadas disponibles en este momento.</p>}</section><section className="section-block"><div className="section-title"><span className="status-dot amber"/><h2>Recuerda</h2><b>{assistant.reminders.length}</b></div>{assistant.reminders.slice(0,8).map(row=><ActionCard key={row.actionKey} row={row}/>)}{!assistant.reminders.length?<p className="empty">Sin recordatorios pasivos.</p>:null}</section>{assistant.used.length?<section className="section-block muted"><div className="section-title"><h2>Ya utilizadas</h2><b>{assistant.used.length}</b></div>{assistant.used.map(row=><div className="used-row" key={row.actionKey}>{row.warscroll.name} · {row.ability.name}</div>)}</section>:null}{assistant.needsReview.length?<section className="review-banner"><strong>{assistant.needsReview.length} regla(s) no se muestran como legales.</strong><span>Su timing no está normalizado con suficiente seguridad.</span></section>:null}<div className="sticky-actions"><button className="primary" onClick={()=>commit({...model,activeGame:nextStep(model.activeGame)})}>Siguiente →</button><button className="secondary" onClick={()=>commit({...model,activeGame:null})}>Cerrar partida</button></div></main>
 }
 if(editingArmy){
  const points=armyPoints(editingArmy),over=points>editingArmy.pointsLimit
  const heroes=editingArmy.units.filter(unit=>catalogById.get(unit.warscrollId)?.keywords.includes('Hero'))
  return <main className="app-shell"><header className="hero compact"><button className="back-link" onClick={()=>commit({...model,editingArmyId:null})}>← Mis ejércitos</button><span className="eyebrow">{editingArmy.faction}</span><h1>{editingArmy.name}</h1><p className={over?'danger-text':''}>{points} / {editingArmy.pointsLimit} pts</p></header><section className="panel"><h2>Añadir unidad</h2><div className="add-row"><select value={selectedWarscrollId} onChange={event=>setSelectedWarscrollId(event.target.value)}>{ogor.warscrolls.map(unit=><option value={unit.id} key={unit.id}>{unit.name} · {unit.points} pts</option>)}</select><button onClick={addUnit}>Añadir</button></div><p className="meta">{ogor.warscrolls.length} warscrolls extraídos automáticamente del dataset v{ogor.source.dataVersion}.</p></section><section className="unit-list">{editingArmy.units.map(unit=>{const warscroll=catalogById.get(unit.warscrollId);return <article className="unit-card" key={unit.instanceId}><div><span className="unit-kicker">{warscroll?.keywords.slice(0,3).join(' · ')}</span><h3>{warscroll?.name}</h3><p>{warscroll?.points} pts · {warscroll?.abilities.length||0} habilidades</p>{unit.isGeneral?<span className="general-badge">GENERAL</span>:null}</div><div className="unit-actions">{warscroll?.keywords.includes('Hero')?<button className="small" onClick={()=>updateArmy({...editingArmy,units:editingArmy.units.map(item=>({...item,isGeneral:item.instanceId===unit.instanceId}))})}>{unit.isGeneral?'General':'Hacer general'}</button>:null}<button className="ghost small" onClick={()=>updateArmy({...editingArmy,units:editingArmy.units.filter(item=>item.instanceId!==unit.instanceId)})}>Quitar</button></div></article>})}{!editingArmy.units.length?<p className="empty">Añade las unidades de tu lista para empezar.</p>:null}</section><section className="validation"><h2>Validación MVP</h2><p>{over?'🔴 Supera el límite de puntos.':'🟢 Puntos dentro del límite.'}</p><p>{heroes.length&&!editingArmy.units.some(unit=>unit.isGeneral)?'🟠 Falta seleccionar general.':'🟢 General comprobado o no aplicable todavía.'}</p></section><div className="sticky-actions"><button className="primary" disabled={!editingArmy.units.length||over} onClick={()=>commit({...model,editingArmyId:null,activeGame:createGameState(editingArmy.id)})}>Iniciar partida</button><button className="secondary" onClick={()=>commit({...model,editingArmyId:null})}>Guardar y volver</button></div></main>
 }
 return <main className="app-shell"><header className="hero"><span className="eyebrow">BATTLE COMPANION</span><h1>Juega la partida.<br/>No contra tu memoria.</h1><p>Asistente mobile-first para saber qué puedes hacer ahora con tu ejército.</p><div className="data-chip">AoS · Ogor Mawtribes · dataset {ogor.source.dataVersion}</div></header><section className="panel"><h2>Nuevo ejército</h2><form className="create-form" onSubmit={createArmy}><label>Nombre<input value={newName} onChange={event=>setNewName(event.target.value)}/></label><label>Límite de puntos<input type="number" min="500" step="250" value={newLimit} onChange={event=>setNewLimit(event.target.value)}/></label><button className="primary" type="submit">Crear ejército</button></form></section><section className="section-block"><div className="section-title"><h2>Mis ejércitos</h2><b>{model.armies.length}</b></div>{model.armies.map(army=><article className="army-card" key={army.id}><div><span className="unit-kicker">{army.faction}</span><h3>{army.name}</h3><p>{armyPoints(army)} / {army.pointsLimit} pts · {army.units.length} unidades</p></div><div className="card-buttons"><button className="primary small" disabled={!army.units.length} onClick={()=>commit({...model,activeGame:createGameState(army.id)})}>Partida</button><button className="secondary small" onClick={()=>commit({...model,editingArmyId:army.id})}>Editar</button><button className="ghost small" onClick={()=>{const copy={...army,id:makeId(),name:`${army.name} (copia)`,units:army.units.map(unit=>({...unit,instanceId:makeId()}))};commit({...model,armies:[...model.armies,copy]})}}>Duplicar</button><button className="ghost small" onClick={()=>commit({...model,armies:model.armies.filter(item=>item.id!==army.id)})}>Eliminar</button></div></article>)}{!model.armies.length?<p className="empty">Todavía no tienes ejércitos guardados.</p>:null}</section><footer><strong>Arquitectura separada del upstream.</strong><span>La base original se lee para generar datos normalizados; no se modifica.</span></footer></main>
}
export default App
