import React, { useMemo, useState } from 'react'
import { PHASES, TURN, createGameState, markAbilityUsed, nextRound, setActivePlayer, setPhase } from './core/gameState'
import { createArmyRepository, exportBattleCompanion, importBattleCompanion, loadBattleCompanion, saveBattleCompanion } from './core/persistence'
import { addRegiment, addUnitToRegiment, createArmy as createArmyModel, createRegiment, getArmyPoints, removeUnitFromRegiment, setArmyGeneral, setBattleFormation, setUnitQuantity, validateArmy } from './core/army'
import { buildBattleAssistant } from './core/battleAssistant'
import { getAbilitiesForArmy, getAbilityPresentation } from './core/armyRules'
import { ogorMawtribesPilot } from './data/ogorMawtribes'
import Styles from './BattleCompanion.module.css'

const phaseEs={DEPLOYMENT:'Despliegue',HERO:'Héroe',MOVEMENT:'Movimiento',SHOOTING:'Disparo',CHARGE:'Carga',COMBAT:'Combate',END:'Final del turno'}
const nextPhase=state=>{const index=PHASES.indexOf(state.phase);if(index<PHASES.length-1)return setPhase(state,PHASES[index+1]);return setActivePlayer(state,state.activePlayer===TURN.YOUR?TURN.OPPONENT:TURN.YOUR)}
const validationText={POINTS_LIMIT_EXCEEDED:'Se supera el límite de puntos.',MULTIPLE_GENERALS:'Solo puede haber un general.',GENERAL_NOT_SELECTED:'Selecciona un general.',GAME_REQUIRED:'Falta el juego.',FACTION_REQUIRED:'Falta la facción.',NAME_REQUIRED:'Falta el nombre.'}
const RuleCard=({item,action})=>{const p=getAbilityPresentation(item.ability);return <article className={Styles.ruleCard} data-card-color={p.cardColor}><div className={Styles.ruleTiming}>{p.timingLabel}</div><div className={Styles.ruleBody}><div className={Styles.ruleTitle}><strong>{item.ability.name}</strong>{p.sourceLabel?<span>{p.sourceLabel}</span>:null}</div>{p.summary?<p>{p.summary}</p>:null}{p.modifiers.length?<div className={Styles.modifiers}>{p.modifiers.map((m,i)=><span key={`${m.label||m}-${i}`}>{m.label||m}</span>)}</div>:null}{action?<button type="button" onClick={action}>✓ Marcar utilizada</button>:null}</div></article>}

const BattleCompanion=()=>{
 const repository=useMemo(()=>createArmyRepository(),[]),persisted=loadBattleCompanion()
 const [armies,setArmies]=useState(repository.list()),[activeGame,setActiveGame]=useState(persisted.activeGame),[editingArmyId,setEditingArmyId]=useState(null)
 const [selectedUnitId,setSelectedUnitId]=useState(ogorMawtribesPilot.units[0]?.id||''),[name,setName]=useState('Mi ejército Ogor'),[points,setPoints]=useState(2000),[backupMessage,setBackupMessage]=useState('')
 const selectableUnits=ogorMawtribesPilot.units.filter(u=>u.validationStatus==='verified_structural'),refresh=()=>setArmies(repository.list())
 const persistArmy=army=>{const saved=repository.save(army);setArmies(repository.list());return saved},persistGame=game=>{const current=loadBattleCompanion();saveBattleCompanion({...current,activeGame:game});setActiveGame(game)}
 const createArmy=e=>{e.preventDefault();repository.save(createArmyModel({name,faction:ogorMawtribesPilot.localeName,factionId:ogorMawtribesPilot.id,gameId:ogorMawtribesPilot.gameId,pointsLimit:Number(points)||2000}));refresh()}
 const openEditor=army=>{let draft={...army,regiments:army.regiments||[],auxiliaryUnits:army.auxiliaryUnits||[]};if(!draft.regiments.length)draft=addRegiment(draft,createRegiment({id:`${army.id}-regiment-1`,name:'Regimiento 1'}));const saved=persistArmy(draft);setEditingArmyId(saved.id)}
 const exportBackup=()=>{const blob=new Blob([exportBattleCompanion()],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='battle-companion-backup.json';a.click();URL.revokeObjectURL(url);setBackupMessage('Copia exportada.')}
 const importBackup=async e=>{const file=e.target.files?.[0];if(!file)return;const result=importBattleCompanion(await file.text());if(!result.ok){setBackupMessage('Archivo no válido.');return}setArmies(result.data.armies);setActiveGame(result.data.activeGame);setBackupMessage('Copia importada correctamente.')}
 if(activeGame){const army=armies.find(a=>a.id===activeGame.armyId),abilities=getAbilitiesForArmy(army,ogorMawtribesPilot.abilities),assistant=buildBattleAssistant(abilities,activeGame),count=assistant.available.length+assistant.reminders.length+assistant.conditional.length,used=a=>persistGame(markAbilityUsed(activeGame,a));return <main className={Styles.shell}><header className={Styles.header}><span className={Styles.eyebrow}>BATTLE COMPANION</span><h1>{army?.name}</h1><p>{ogorMawtribesPilot.localeName}{army?.battleFormation?.name?` · ${army.battleFormation.name}`:''}</p></header><section className={Styles.statusGrid}><div><span>Ronda</span><strong>{activeGame.round}</strong></div><div><span>Turno</span><strong>{activeGame.activePlayer===TURN.YOUR?'Mi turno':'Turno rival'}</strong></div><div><span>Fase</span><strong>{phaseEs[activeGame.phase]||activeGame.phase}</strong></div></section><section className={Styles.phaseHero}><span>AHORA</span><h2>{phaseEs[activeGame.phase]||activeGame.phase}</h2><p>{count?`${count} cosa(s) que recordar de tu ejército.`:'No tienes acciones ni reglas de tu ejército que recordar en esta fase.'}</p></section><section className={Styles.panel}><h2>Acciones disponibles</h2>{assistant.available.length?assistant.available.map(x=><RuleCard key={x.ability.abilityId} item={x} action={()=>used(x.ability)}/>):<p>Ninguna acción disponible ahora.</p>}</section><section className={Styles.panel}><h2>No olvides</h2>{assistant.reminders.length?assistant.reminders.map(x=><RuleCard key={x.ability.abilityId} item={x}/>):<p>Sin recordatorios aplicables.</p>}</section><section className={Styles.panel}><h2>Si se cumple...</h2>{assistant.conditional.length?assistant.conditional.map(x=><RuleCard key={x.ability.abilityId} item={x} action={()=>used(x.ability)}/>):<p>Sin reglas condicionales aplicables.</p>}</section><div className={Styles.actions}><button onClick={()=>persistGame(nextPhase(activeGame))}>Siguiente fase</button><button className={Styles.secondary} onClick={()=>persistGame(nextRound(activeGame))}>Siguiente ronda</button><button className={Styles.ghost} onClick={()=>persistGame(null)}>Cerrar partida</button></div></main>}
 const editingArmy=armies.find(a=>a.id===editingArmyId)
 if(editingArmy){const validation=validateArmy(editingArmy),regiment=editingArmy.regiments[0],add=()=>{const unit=selectableUnits.find(u=>u.id===selectedUnitId);if(unit&&regiment)persistArmy(addUnitToRegiment(editingArmy,regiment.id,unit))};return <main className={Styles.shell}><header className={Styles.header}><span className={Styles.eyebrow}>{ogorMawtribesPilot.localeName}</span><h1>{editingArmy.name}</h1><p>{validation.points} / {editingArmy.pointsLimit} pts</p></header><section className={Styles.panel}><h2>Formación de batalla</h2><select value={editingArmy.battleFormation?.id||''} onChange={e=>persistArmy(setBattleFormation(editingArmy,ogorMawtribesPilot.battleFormations.find(f=>f.id===e.target.value)||null))}><option value="">Seleccionar formación</option>{ogorMawtribesPilot.battleFormations.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></section><section className={Styles.panel}><h2>Añadir unidad</h2><div className={Styles.inlineControls}><select value={selectedUnitId} onChange={e=>setSelectedUnitId(e.target.value)}>{selectableUnits.map(u=><option key={u.id} value={u.id}>{u.name} · {u.points} pts</option>)}</select><button type="button" onClick={add}>Añadir</button></div></section><section className={Styles.panel}><h2>{regiment?.name}</h2>{regiment?.units.length?regiment.units.map(u=><div className={Styles.unitRow} key={u.instanceId}><div><strong>{u.name}</strong><span>{u.points} pts × {u.quantity}</span>{u.isGeneral?<span className={Styles.generalBadge}>GENERAL</span>:null}</div><div className={Styles.unitControls}><input type="number" min="1" value={u.quantity} onChange={e=>persistArmy(setUnitQuantity(editingArmy,regiment.id,u.instanceId,e.target.value))}/>{u.keywords?.includes('Hero')?<button type="button" className={Styles.secondary} onClick={()=>persistArmy(setArmyGeneral(editingArmy,u.instanceId))}>{u.isGeneral?'General':'Hacer general'}</button>:null}<button type="button" className={Styles.ghost} onClick={()=>persistArmy(removeUnitFromRegiment(editingArmy,regiment.id,u.instanceId))}>Quitar</button></div></div>):<p>Añade las unidades que llevas realmente a la partida.</p>}</section><section className={Styles.panel}><h2>Validación</h2>{[...validation.errors,...validation.warnings].map(c=><p key={c}>⚠️ {validationText[c]||c}</p>)}</section><div className={Styles.actions}><button onClick={()=>setEditingArmyId(null)}>Guardar y volver</button></div></main>}
 return <main className={Styles.shell}><header className={Styles.header}><span className={Styles.eyebrow}>BATTLE COMPANION</span><h1>Mis ejércitos</h1><p>Age of Sigmar · {ogorMawtribesPilot.localeName}</p></header><form className={Styles.panel} onSubmit={createArmy}><h2>Crear ejército Ogor</h2><label>Nombre<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Límite de puntos<input type="number" value={points} onChange={e=>setPoints(e.target.value)}/></label><button>Crear ejército</button></form><section className={Styles.list}>{armies.map(a=><article className={Styles.armyCard} key={a.id}><div><span className={Styles.eyebrow}>{ogorMawtribesPilot.localeName}</span><h2>{a.name}</h2><p>{getArmyPoints(a)} / {a.pointsLimit} pts</p></div><div className={Styles.cardActions}><button onClick={()=>persistGame(createGameState({armyId:a.id}))}>Iniciar partida</button><button className={Styles.secondary} onClick={()=>openEditor(a)}>Editar ejército</button><button className={Styles.ghost} onClick={()=>{repository.remove(a.id);refresh()}}>Eliminar</button></div></article>)}</section><section className={Styles.panel}><h2>Copia de seguridad</h2><div className={Styles.cardActions}><button type="button" onClick={exportBackup}>Exportar JSON</button><label className={Styles.fileButton}>Importar JSON<input type="file" accept=".json" onChange={importBackup}/></label></div>{backupMessage?<p>{backupMessage}</p>:null}</section></main>
}
export default BattleCompanion
